name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        node: [16]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

      - run: pnpm i
      - run: pnpm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          publish_dir: ./public
          force_orphan: true
